//TODO: add all the action types here only
export const POST_REGISTER_REQUEST = "POST_REGISTER_REQUEST";
export const POST_REGISTER_REQUEST_SUCCESS = "POST_REGISTER_REQUEST_SUCCESS";
export const POST_REGISTER_REQUEST_FAILURE = "POST_REGISTER_REQUEST_FAILURE";
