//TODO: add all the action types here only
export const POST_REGISTER_REQUEST = "POST_REGISTER_REQUEST";
export const POST_REGISTER_REQUEST_SUCCESS = "POST_REGISTER_REQUEST_SUCCESS";
export const POST_REGISTER_REQUEST_FAILURE = "POST_REGISTER_REQUEST_FAILURE";



// Admin page Request
export const ADMIN_PRODUCT_REQUEST = "ADMIN_PRODUCT_REQUEST"
export const ADMIN_PRODUCT_SUCCESS = "ADMIN_PRODUCT_SUCCESS"
export const ADMIN_PRODUCT_FAILURE = "ADMIN_PRODUCT_FAILURE"
export const ADMIN_POST_PRODUCT__SUCCESS = "ADMIN_POST_PRODUCT__SUCCESS"
export const ADMIN_PATCH_PRODUCT_SUCCESS = "ADMIN_PATCH_PRODUCT_SUCCESS"
